/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  collections: {
    users: User;
    media: Media;
    service: Service;
    journal: Journal;
    case: Case;
    about: About; 
    hosting: Hosting;
    development: Development;
    ai: Ai;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;

  };
  db: {
    defaultIDType: string;
  };
  globals: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
}

export interface Development {
  id: string;
  title: string;
  description: string;
  image: Media | string | null;
  content: any;
}




export interface Journal {
  id: number;
  title: string;
  slug: string;
  featuredImage: Media;
  excerpt: string;
  content: any;
  author: string;
  publishedDate: string;
  categories?: Array<{ category: string }>;
  status: 'draft' | 'published';
  createdAt: string;
  updatedAt: string;  
}

export interface Service {
  id: string;
  title: string;
  description: string;
  image: Media | string | null;
  link?: string;
  icon?: Media | string | null; 
  slug: string;
}

export interface Branding {
  id: string;
  title: string;
  description: string;
  image: Media | string | null;
  content: any;
} 

export interface Case {   
  id: string;
  title: string;
  description: string;
  image: Media | string | null;
  url: string;
  slug: string;
  about: string;
  services: string;
  headingProject: string;
  descriptionProject: string;
  caseScreens: Media | string | null;
  backgroundImage: Media | string | null;
  procesDescription: string;
  procesImage: Media | string | null;
  procesImageCaption: string;
  resultText: string;
  resultImage: Media | string | null;
  resultImageCaption: string;
  resultImage2: Media | string | null;
  resultImageCaption2: string;
  usedTechniques: string;
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;  
}

export interface About {
  id: string;
  title: string;
  content: any;
  image: Media | string | null;
  link?: string;
}

export interface Ai {
  id: string;
  title: string;
  content: any;
  image: Media | string | null; 
}

export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}

export interface Hosting {
  id: string;
  title: string;
  description: string;
  image: Media | string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}

/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}

/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}

/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}

/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}

declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}