import { ICaseData } from './types';

export const caseData: ICaseData[] = [
    {
        id: 1, // Numeric ID
        title: 'JodaroGym',
        description: 'JodaroGym is een kickboksschool biedt een omgeving waarin zowel beginners als gevorderden zich kunnen ontwikkelen en hun doelen kunnen bereiken.',
        image: '/cases/jodaro/jodaroscreens.png',     
        url: 'https://www.jodarogym.nl',        
        about: 'Bij Jodaro Gym geloven we dat vechtsporten meer zijn dan alleen een fysieke uitdaging; het is een levensstijl die discipline, zelfvertrouwen en een sterk gemeenschapsgevoel bevordert. Onze boks- en kickboksschool biedt een omgeving waarin zowel beginners als gevorderden zich kunnen ontwikkelen en hun doelen kunnen bereiken.',
        services: 'UX Design, UI Design, Wordpress , Hosting , Onderhoud',
        headingProject: 'Een nieuwe website voor JodaroGym',
        descriptionProject: 'De vraag vanuit JodaroGym voor de website ging over vindbaarheid en een nieuwe visie op de website./n Er werd door klanten veel gebeld omdat de website geen duidelijkheid gaf. Met een geheel nieuw ontwerp waar je alle informatie eenvoudig kan vinden, is de conversie op de website gestegen. Daarnaast is er nu ook direct de mogelijkheid voor bestaande leden om via de website hun in te schrijven voor de lessen.',
        caseScreens: '/cases/jodaro/jodaroscreens.png',            
        backgroundImage: '/cases/jodaro/jodaroscreens.png',
        procesDescription: 'Het proces voor de nieuwe website van Jodaro Gym begon met een grondige analyse van de huidige website en het identificeren van verbeterpunten op basis van gebruiksvriendelijkheid en inhoud. Samen met het team van Jodaro Gym hebben we een concept ontwikkeld dat zowel de visuele als functionele identiteit van de sportschool weerspiegelt.Vervolgens gingen we aan de slag met het ontwerp, waarbij de nadruk lag op een dynamische, sportieve look en een logische structuur die bezoekers gemakkelijk naar de juiste informatie leidt. Na de ontwerp- en feedbackrondes werd de website in fases opgebouwd en getest, zodat elke functionaliteit vlekkeloos werkt op alle apparaten.Het resultaat is een website waar Jodaro Gym trots op kan zijn en die de klanten de beste online ervaring biedt. Dankzij nauw overleg en een iteratief ontwikkelproces is de site een krachtige, digitale verlenging van de sportschool geworden.', 
        procesImage:'/cases/jodaro/figma_jodaro.png',
        procesImageCaption: 'Navigation',
        resultText:'De nieuwe website van Jodaro Gym is ontwikkeld met de gebruiker in gedachten en biedt een sterke, moderne uitstraling die perfect past bij de energie van de sportschool. Met verbeterde navigatie, duidelijke informatie over lessen en tarieven, en een overzicht van de trainers is het nu eenvoudiger dan ooit om een passende training te vinden. De website werkt soepel op alle apparaten, zodat bezoekers op elk moment kunnen inloggen voor het laatste nieuws en updates. Jodaro Gym is klaar om sporters te inspireren met een online ervaring die net zo motiverend is als hun trainingen',
        resultImage: '/cases/jodaro/jodaro_old.png',
        resultImageCaption: 'Vorige Website',
        resultImage2: '/cases/jodaro/jodaro_new.png',
        resultImageCaption2: 'Nieuwe Website',
        usedTechniques: 'Figma, Wordpress, Elementor , PHP, Adobe Creative Suite, SEO,AddWords',
    },              
    {
        id: 2, // Numeric ID
        title: 'Broeders Leefstijl',                        
        description: 'Live trainingen en workshops om je reis naar vitaliteit starten.',
        image: '/cases/broeders/broeders.png',
        url: 'https://www.broedersleefstijl.nl',
        about: `De Broeders Leefstijl Academy biedt een breed scala aan diensten gericht op het verbeteren van de fysieke en mentale gezondheid van individuen en teams. De academy richt zich zowel op persoonlijke als zakelijke begeleiding en biedt op maat gemaakte programma's en workshops aan.`,
        services: 'UX Design, UI Design, Webdevelopment',
        caseScreens: '/cases/broeders/broedersbanner1.png',
        backgroundImage: '/cases/broeders/broedersbackground.png',
        headingProject: 'Een compleet nieuwe website voor Broeders Leefstijl',
        procesImage:'/cases/broeders/figmabroeders.png',
        procesImageCaption: 'Information Architecture',
        descriptionProject: 'Broeders Leeftstijl is een platform om hulp bij het bereiken van een gezonde levensstijl.',
        procesDescription: 'Het proces voor de website van Broeders Leefstijl begon met een grondige kennismaking met de verschillende diensten die zij aanbieden, waaronder Broeders IJsbaden en Bodyproof Fysiotherapie. We werkten nauw samen met het team om de essentie van elk merk vast te leggen en een design te creëren dat zowel de diversiteit van hun aanbod weerspiegelt als een samenhangende gebruikerservaring biedt.Na de conceptfase gingen we aan de slag met het ontwerp, waarbij we de visuele identiteit van de verschillende onderdelen van de website zorgvuldig combineerden. Het ontwerp moest enerzijds de professionaliteit en expertise van de fysiotherapie uitstralen, terwijl het anderzijds de energieke en motiverende sfeer van de ijsbaden weerspiegelde. We zorgden ervoor dat de navigatie logisch en eenvoudig was, zodat bezoekers snel de informatie vonden die ze zochten.Het resultaat is een visueel aantrekkelijk, goed gestructureerd ontwerp dat niet alleen het merk van Broeders Leefstijl versterkt, maar ook de gebruikerservaring optimaliseert voor zowel nieuwe klanten als bestaande gebruikers.', 
        resultText: 'Het eindresultaat is een website die niet alleen de diensten van Broeders Leefstijl effectief presenteert, maar ook de nadruk legt op hun workshops, zowel voor bedrijven als individuele deelnemers. Of het nu gaat om online workshops of persoonlijke sessies, het ontwerp maakt het eenvoudig voor bezoekers om meer te leren over de verschillende mogelijkheden en direct in te schrijven. Door de duidelijke en gestructureerde indeling kunnen bedrijven en particulieren snel de workshops vinden die aansluiten bij hun behoeften. Deze toevoeging versterkt de positie van Broeders Leefstijl als expert in het bieden van zowel fysieke als digitale oplossingen voor welzijn en persoonlijke ontwikkeling.',
        resultImage: '/cases/broeders/homebroeders.png',
        resultImageCaption: 'Figma Design',
        resultImage2: '/cases/broeders/broedersleefstijl-nl.png',
        resultImageCaption2: 'Live Website',
        usedTechniques: 'Figma, Adobe Creative Suite, Wordpress',
    },          

    {
        id: 3, // Numeric ID
        title: 'RedFlowerTemple',
        description: 'Red Flower Temple, your ultimate destination for premium Japanese art supplies.',         
        image: '/cases/RFT/rftscreen.png',
        url: 'https://www.redflowertemple.com',
        about: 'RedFlowerTemple is the store for premium Japanese art supplies.',
        services: 'UX Design, Shopify, Information Architecture, SEO',
        caseScreens: '/cases/rft/rft-screen.png',
        backgroundImage: '/cases/rft/rftscreen.png',       
        headingProject: 'Restructure and adjust RedFlowerTemple',
        descriptionProject: 'Voor RedFlowerTemple was het belangrijk om de navigatie te verbeteren en de informatiearchitektuur aan te passen. Producten zijn nu gerangschikt in nieuwe Shopify Collections.',
        procesImage:'/cases/rft/rftoldnav.png',
        procesImageCaption: 'Navigation',
        procesDescription: 'Voor de aangepaste website van Red Flower Temple hebben we gewerkt aan een verbeterde gebruikerservaring en een verfijnde uitstraling die de kernwaarden van de tempel nog sterker naar voren brengt. Tijdens het proces hebben we de bestaande content en structuur geanalyseerd en samen met het team de punten aangepakt die verbetering nodig hadden.De aanpassingen omvatten een overzichtelijkere navigatie, geoptimaliseerde secties voor belangrijke informatie en een visuele update die aansluit bij de rustige, spirituele sfeer van Red Flower Temple. Deze verbeteringen zorgen ervoor dat bezoekers de weg naar inspiratie en informatie sneller en prettiger vinden.',
        resultText: 'Het resultaat is een website die nu beter aansluit bij de behoeften van bezoekers die op zoek zijn naar hoogwaardige Japanse art supplies,prints en inspiratieboeken. Door de verbeterde navigatie en gebruiksvriendelijke structuur kunnen klanten sneller vinden wat ze nodig hebben. De visuele update maakt de website moderner en overzichtelijker, waardoor het winkelen voor materialen en het ontdekken van boeken voor creatieve inspiratie een prettige ervaring is. Deze aanpassingen ondersteunen Red Flower Temple in het verder versterken van hun online aanwezigheid en het bieden van waardevolle producten aan hun klanten.',
        resultImage: '/cases/rft/rftbefore.png',
        resultImageCaption: 'Vorige Website',
        resultImage2: '/cases/rft/redflowertemple.png',
        resultImageCaption2: 'Live Website',
        usedTechniques: 'Shopify, Figma, Adobe Creative Suite',
    },
   
];
