import { ICaseData } from './types';

export const caseData: ICaseData[] = [
    {
        id: 1, // Numeric ID
        title: 'JodaroGym',
        description: 'JodaroGym is een kickboksschool biedt een omgeving waarin zowel beginners als gevorderden zich kunnen ontwikkelen en hun doelen kunnen bereiken.',
        image: '/cases/jodaro/jodaroscreens.png',     
        url: 'https://www.jodarogym.nl',
        about: 'Bij Jodaro Gym geloven we dat vechtsporten meer zijn dan alleen een fysieke uitdaging; het is een levensstijl die discipline, zelfvertrouwen en een sterk gemeenschapsgevoel bevordert. Onze boks- en kickboksschool biedt een omgeving waarin zowel beginners als gevorderden zich kunnen ontwikkelen en hun doelen kunnen bereiken.',
        services: 'UX Design, UI Design, Wordpress , Hosting , Onderhoud',
  
        headingProject: 'Een nieuwe website voor JodaroGym',
        descriptionProject: 'De vraag vanuit JodaroGym voor de website ging over vindbaarheid en een nieuwe visie op de website./n Er werd door klanten veel gebeld omdat de website geen duidelijkheid gaf. Met een geheel nieuw ontwerp waar je alle informatie eenvoudig kan vinden, is de conversie op de website gestegen. Daarnaast is er nu ook direct de mogelijkheid voor bestaande leden om via de website hun in te schrijven voor de lessen.',
        caseScreens: '/cases/jodaro/jodaroscreens.png',            
        backgroundImage: '/cases/jodaro/jodaroscreens.png',
        resultImage: '/cases/jodaro/jodaro_old.png',
        resultImage2: '/cases/jodaro/jodaro_new.png',   
        usedTechniques: 'UX Design, UI Design, Wordpress , Hosting , Onderhoud',
    },    
    {
        id: 2, // Numeric ID
        title: 'Broeders Leefstijl',                        
        description: 'Live trainingen en workshops om je reis naar vitaliteit starten.',
        image: '/cases/broeders.png',
        url: 'https://www.broedersleefstijl.nl',
        about: 'Live trainingen en workshops om je reis naar vitaliteit starten. Ontdek boeiende sessies geleid door gezondheidsexperts.  Klaar om te leren, groeien en stralen? Laten we samen aan de slag gaan!',
        services: 'UX Design, UI Design, Webdevelopment',
        caseScreens: '/cases/broedersleefstijl-xs.png',
        backgroundImage: '/cases/broedersleefstijl-xs.png',
        headingProject: 'Een nieuw platform voor Broeders Leeftstijl',
        descriptionProject: 'Broeders Leeftstijl is een platform om hulp bij het bereiken van een gezonde levensstijl.',
        resultImage: '/cases/broedersleefstijl-new.png',
        resultImage2: '/cases/broedersleefstijl-old.png',
        usedTechniques: 'UX Design, UI Design, Webdevelopment',
    },          

    {
        id: 3, // Numeric ID
        title: 'RedFlowerTemple',
        description: 'Red Flower Temple, your ultimate destination for premium Japanese art supplies.',         
        image: '/cases/rft/rft-screen.png',
        url: 'https://www.redflowertemple.com',
        about: 'RedFlowerTemple is the store for premium Japanese art supplies.',
        services: 'UX Design, Shopify, Information Architecture',
        caseScreens: '/cases/rft/rft-screen.png',
        backgroundImage: '/cases/rft/rft-screen.png',
        headingProject: 'Restructure and adjust RedFlowerTemple',
        descriptionProject: 'RedFlowerTemple is the store for premium Japanese art supplies.',
        resultImage: '/cases/rft/rft_before.png',
        resultImage2: '/cases/rft/RedFlowerTemple.png',
        usedTechniques: 'Shopify, Figma',
    },
    {
        id: 4, // Numeric ID    
        title: 'NFI',
        description: 'Nederlands Forensisch Instituut,het NFI is een internationaal kennis- en expertisecentrum voor forensisch onderzoek.',
        image: '/cases/rijksoverheid.svg',
        url: 'https://www.forensischinstituut.nl',
        about: 'NFI is een platform voor onderzoekers en ontwikkelaars om te delen en te co-creëren.',
        services: 'UX Design, UI Design, Webdevelopment, Design System',
        caseScreens: '/cases/nfiscreens.png',
        backgroundImage: '/cases/nfiscreens.png',
        headingProject: 'Een nieuwe website voor NFI',
        descriptionProject: 'NFI is een platform voor onderzoekers en ontwikkelaars om te delen en te co-creëren.',
        resultImage: '/cases/nfi/nfi-new.png',
        resultImage2: '/cases/nfi/nfi-old.png',
        usedTechniques: 'UX Design, UI Design, Webdevelopment, Design System',
    },
    {
        id: 5, // Numeric ID
        title: 'TotheRoot',
        description: 'TotheRoot is a platform for developers to share and contribute.',
        image: '/cases/totheroot.svg',
        url: 'https://www.totheroot.io',
        about: 'TotheRoot is een platform voor onderzoekers en ontwikkelaars om te delen en te co-creëren.',
        services: 'UX Design, UI Design, Webdevelopment',
            caseScreens: '/cases/totherootscreens.png',
        backgroundImage: '/cases/totherootscreens.png',
        headingProject: 'Een nieuwe website voor TheRoot',
        descriptionProject: 'TotheRoot is een platform voor onderzoekers en ontwikkelaars om te delen en te co-creëren.',
        resultImage: '/cases/totheroot/totheroot-old.png',
        resultImage2: '/cases/totheroot/totheroot-new.png',
        usedTechniques: 'UX Design, UI Design, Webdevelopment',
    },
    {
        id: 6, // Numeric ID
        title: 'De Volksbank',
        description: 'De Volksbank is het moederbedrijf van SNS, ASN Bank, RegioBank en BLG Wonen',
        image: '/cases/volksbank.svg',
        url: 'https://www.volksbank.nl',
        about: 'De Volksbank is een platform voor onderzoekers en ontwikkelaars om te delen en te co-creëren.',
        services: 'Webdevelopment, Design System',
   
            caseScreens: '/cases/volksbankscreens.png',
        backgroundImage: '/cases/volksbankscreens.png',
        headingProject: 'Een nieuwe website voor De Volksbank',
        descriptionProject: 'De Volksbank is een platform voor onderzoekers en ontwikkelaars om te delen en te co-creëren.',
        resultImage: '/cases/volksbank/volksbank-new.png',
        resultImage2: '/cases/volksbank/volksbank-old.png',
        usedTechniques: 'UX Design, UI Design, Webdevelopment, Design System',
    },
    {
        id: 7, // Numeric ID
        title: 'Megaparsec',
        description: 'Megaparsec is actief in de branche Advisering en ondersteuning op het gebied van informatietechnologie, de specialist in Cloud Consultancy.',
        image: '/cases/MPS.jpg',
        url: 'https://www.megaparsec.nl',
        about: 'Megaparsec is een platform voor onderzoekers en ontwikkelaars om te delen en te co-creëren.',
        services: 'UX Design, UI     Design, Webdevelopment , Hosting , Onderhoud',

        caseScreens: '/cases/megaparsecscreens.png',
        backgroundImage: '/cases/megaparsecscreens.png',
        headingProject: 'Een nieuwe website voor Megaparsec',
        descriptionProject: 'Megaparsec is een platform voor onderzoekers en ontwikkelaars om te delen en te co-creëren.',
        resultImage: '/cases/megaparsec/megaparsec-new.png',
        resultImage2: '/cases/megaparsec/megaparsec-old.png',
        usedTechniques: 'UX Design, UI Design, Webdevelopment , Hosting , Onderhoud',
    },

    {
        id: 8, // Numeric ID
        title: 'Redora',                        
        description: 'Redora levert standaard mobiele oplossingen voor Gemeenten en Politie: Bekeuren: Fiscaal en Strafrechtelijk. Waarschuwen. Melden: Openbare ruimte en Bestuurlijke afhandeling.',
        image: '/cases/redora_logo.jpeg',
        url: 'https://www.twyns.com',
        about: 'Redora is een platform voor onderzoekers en ontwikkelaars om te delen en te co-creëren.',
        services: 'UX Design, UI Design, Webdevelopment',
        caseScreens: '/cases/redorascreens.png',
        backgroundImage: '/cases/redorascreens.png',
        headingProject: 'Een nieuwe website voor Redora',
            descriptionProject: 'Redora is een platform voor onderzoekers en ontwikkelaars om te delen en te co-creëren.',
        resultImage: '/cases/redora/redora-new.png',
        resultImage2: '/cases/redora/redora-old.png',
        usedTechniques: 'UX Design, UI Design, Webdevelopment',
    },
];
